### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by victorhck** [ResonantWave/charla-lignux#1]
Me alegro si te sirvieron algunas diapositivas para incluirlas en tu presentación!! :)

Happy hacking!!

**Comment by ResonantWave** [comment]
Acabo de corregir los agradecimientos del readme; no era consciente de que las diapositivas eran originalmente tuyas.

Un saludo y gracias por tu trabajo!

**Comment by victorhck** [comment]
Hola!
No era necesario... Las diapositivas no son mías, simplemente las adapte y traduje al español por si a alguien le servían.

Salud!!
